c1, c2 = st.columns([7,3])
st.caption("Charla:")
st.markdown("# Construí esto, pero...  _¿Cómo lo comparto?_")
st.markdown("## Sebastián Flores, 10 Junio 2022")
st.markdown("### 1000 Programadores Salteños")
st.write("Repo: https://github.com/sebastiandres/talk_2022_06_1000PS")
st.image("images/1000PS.png", width=400)
